bootstrap:
  build: .
  hostname: cluster-bootstrap
  command: --wsrep-node-name=Dock1 --skip-grant-tables --wsrep-new-cluster
  environment:
    MYSQL_ROOT_PASSWORD: 'toor'
  ports:
      - "3306"
      - "4567"
      - "4568"
member:
  build: .
  command: --wsrep_cluster_address=gcomm://bootstrap --skip-grant-tables --wsrep-sst-method=rsync
  environment:
    MYSQL_ROOT_PASSWORD: 'toor'
  links:
      - bootstrap:bootstrap
  ports:
      - "3306"
      - "4567"
      - "4568"
